---
- name: Create a new Demo EC2 instance
  hosts: localhost
  gather_facts: False

  vars:
      region:
      ami:
      name:
      security_group:
      Instance_type:
      ADFS_Role:
      Business_Unit:
      Environment:
      OS:
      Project:
      Project_Code:
      Start_Date:
      VM_Owner:
      vpc_id:
      End_date:
      vpc_subnet_id:
  tasks:
  
    - name:  security group creation
      ec2_group:
        name: "{{ security_group }}"
        description: sg with ssh access from management VPC
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            ports:
            - 22
            cidr_ip: 0.0.0.0/0
    - name: Create an ec2 instance
      ec2:
         key_name: DigitizeEdge-21-Aug-14
         group: "{{ security_group }}"  # security group name
         instance_type: "{{ Instance_type }}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 1  # default
         instance_tags:
            Name: "{{ name }}"
            ADFS Role: "{{ ADFS_Role }}"
            Business Unit: "{{ Business_Unit }}"
            Environment: "{{ Environment }}"
            OS: "{{ OS }}"
            Project: "{{ Project }}"
            Project Code: "{{ Project_Code }}"
            Start Date: "{{ Start_Date }}"
            VM Owner: "{{ VM_Owner}}"
            End Date: "{{ End_date }}"
         vpc_subnet_id: "{{ vpc_subnet_id }}"
         assign_public_ip: no
      register: ec2

