 - name: Create a new ELB
   hosts: localhost
   gather_facts: False
   tasks:
  - local_action:
    module: ec2_elb_lb
    name: "name"
    state: present
    zones:
      - us-east-1a
      - us-east-1c
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 80
    subnets: 'subnet-123abc,subnet-456def'
    health_check:
        ping_protocol: http 
        ping_port: 8000
        ping_path: "/" 
        response_timeout: 5 
        interval: 30 
        unhealthy_threshold: 2
        healthy_threshold: 10
    tags:
        Name: "name1"